<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Address' => 'Адрес',
    'Adoptiondate' => 'Дата добавления',
    'Are you sure you want to delete this item?' => 'Вы уверены, что хотите удалить  запись?',
    'Count' => 'Количество',
    'Create Employee' => 'Добавить сотрудника',
    'Create Material' => 'Добавить материал',
    'Create Partner' => 'Добавить контрагента',
    'Create Position' => 'Добавить должность',
    'Create Storehouse' => 'Добавить склад',
    'Create Unit' => 'Добавить отдел',
    'Delete' => 'Удалить',
    'Description' => 'Описание',
    'Email' => 'Электронная почта',
    'Employees' => 'Сотрудники',
    'Home' => 'Главная',
    'ID' => 'Идентификатор',
    'Idemployee' => 'ИН пользователя',
    'Idmaterial' => 'ИН материала',
    'Idposition' => 'ИН должности',
    'Idstorehouse' => 'ИН склада',
    'Idunit' => 'ИН отдела',
    'Login' => 'Вход',
    'Logout' => 'Выход',
    'Materials' => 'Материалы',
    'Name' => 'Имя сотрудника',
    'Notice' => 'Дополнительно',
    'Partners' => 'Контрагенты',
    'Position Idposition' => 'Должность',
    'Positions' => 'Должности',
    'Positiontname' => 'Наименование должности',
    'Price' => 'Стоимость',
    'Reset' => 'Отмена',
    'Responsible Person' => 'Отвественный',
    'Save' => 'Сохранить',
    'Search' => 'Поиск',
    'Secondname' => 'Фамилия',
    'Storehouse Idstorehouse' => 'Склад',
    'Storehouses' => 'Склады',
    'The requested page does not exist.' => 'Запрашиваемая страница не существует',
    'Timestamp' => 'Дата и время',
    'Unitname' => 'Наименование отдела',
    'Units' => 'Отделы',
    'Update' => 'Обновить',
    'Update Employee: {name}' => 'Обновить данные сотрудника: {name}',
    'Update Material: {name}' => 'Обновить данные материала: {name}',
    'Update Partner: {name}' => 'Обновить данные контрагента: {name}',
    'Update Position: {name}' => 'Обновить данные должности: {name}',
    'Update Storehouse: {name}' => 'Обновить данные склада: {name}',
    'Update Unit: {name}' => 'Обновить данные отдела: {name}',
    'Storehouse Name' => '',
    'Адрес контрагента' => '',
    'Город' => '',
    'Контактный номер телефона' => '',
    'Наименование партнера' => '',
    'Серия и номер паспорта агента' => '',
    'ФИО агента' => '',
    'About' => '@@О системе@@',
    'Contact' => '@@Контакты@@',
    'Idstorehouse,' => '@@@@',
    'Position' => '@@Должность@@',
];
