<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => 'О системе',
    'Contact' => 'Контакты',
    'Create Partner' => 'Добавить контрагента',
    'Home' => 'Главная',
    'Login' => 'Вход',
    'Logout' => 'Выход',
    'Partners' => 'Контрагенты',
    'Save' => 'Сохранить',
    'Are you sure you want to delete this item?' => '',
    'Create Employee' => 'Добавить сотрудника',
    'Delete' => '',
    'Email' => '',
    'Employees' => 'Сотрудники',
    'ID' => '',
    'Idemployee' => '',
    'Idposition' => '',
    'Name' => '',
    'Position Idposition' => '',
    'Positiontname' => '',
    'Reset' => '',
    'Search' => '',
    'Secondname' => '',
    'The requested page does not exist.' => '',
    'Timestamp' => '',
    'Update' => '',
    'Update Employee: {name}' => '',
    'Update Partner: {name}' => '',
    'Адрес контрагента' => '',
    'Город' => '',
    'Контактный номер телефона' => '',
    'Наименование партнера' => '',
    'Серия и номер паспорта агента' => '',
    'ФИО агента' => '',
];
